version: "3.8"
services:
  db:
    container_name: postgres_container2
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  go_app:
    container_name: go_app_container
    build: C:\Users\leona\Documents\Practice\TwichtCHatAPp\TwitchChatApp
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      OAUTH_TOKEN: "oauth:w6u9na8pejq46btedmwia86zadhzy9"
      TWITCH_USERNAME: "gomes3567"
      TWITCH_CHANNEL: "quin69"
    links:
      - db:postgres_container2

  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - "8081:80"
